/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:deb5e5e9-6d25-4f44-ba51-9e07e9438886",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_zqgZPUsZ1",
    "aws_user_pools_web_client_id": "1b2ehkb71arrea7823j04es7tc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pylohldgnzaf5hrnsq6e7mobjq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-eahm7lk2tnc7nee4bxbozykugm",
    "aws_user_files_s3_bucket": "amplifyappbf7e6ef5090a4dab9422ee4894b0ef08143431-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
